[package]
name = "broken"
version = "1.0.0"
authors = ["The Sync Team <sync-team@mozilla.com>"]
edition = "2018"
description = "Something is broken"
readme = "README.md"
license = "MPL-2.0"

[lib]
name = "broken"
crate-type = ["lib", "cdylib"]
